// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AgentConfig>;

export function GetStatus():Promise<string>;

export function SaveConfig(arg1:main.AgentConfig):Promise<void>;

export function SetStatus(arg1:string):Promise<void>;

export function StartAgent(arg1:string,arg2:string):Promise<void>;

export function StopAgent():Promise<void>;
