// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}

export function StartAgent(arg1, arg2) {
  return window['go']['main']['App']['StartAgent'](arg1, arg2);
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}
